// answer-engine.mjs
//
// Maps a Greenhouse application form (the JSON returned by
// boards-api.greenhouse.io/.../jobs/{id}?questions=true) to concrete answers,
// using ONLY the applicant's saved profile for high-stakes fields and (later)
// AI for free-text. Every answer carries a source + confidence so the verifier
// can refuse to submit anything uncertain.
//
// Design rule for "no mistakes": when in doubt, DO NOT ANSWER. An unanswered
// required field parks the whole job for manual review instead of guessing.

/** Answer sources, most→least trustworthy. */
export const SOURCE = {
  PROFILE: "profile", // copied verbatim from saved settings — highest trust
  RESUME: "resume", // pulled from parsed resume
  RULE: "rule", // deterministic mapping (e.g. "worked here before" → No)
  AI: "ai", // generated by the model (free-text only)
  NONE: "none", // could not answer → forces review
};

const norm = (s) => (s || "").toString().trim().toLowerCase();

// Factually-equivalent country label variants. Safe to treat as identical —
// a form calling it "United States of America" and a profile saying "United
// States" are the same country, not a guess.
const COUNTRY_SYNONYMS = [
  ["united states", "united states of america", "usa", "u.s.a.", "u.s.", "us"],
  ["united kingdom", "uk", "u.k.", "great britain"],
];
function countryVariants(value) {
  const v = norm(value);
  const group = COUNTRY_SYNONYMS.find((g) => g.includes(v));
  return group ? group : [v];
}

/** Find the select option whose label matches `desired` (case-insensitive).
 *  Returns the option's stored value, or null if there is no exact match.
 *  We never fuzzy-pick a "close" option — a wrong compliance pick is the exact
 *  mistake we must avoid. */
function matchOption(field, desired, { synonyms = null } = {}) {
  const values = field.values || field.options || [];
  const wants = synonyms || [norm(desired)];
  const hit = values.find((v) => wants.includes(norm(v.label)));
  if (hit) return { value: hit.value, label: hit.label };
  return null;
}

/** Classify a custom question by its label so we can route it to the right
 *  profile field. Returns a key or null. Order matters (first match wins). */
function classify(label) {
  const l = norm(label);
  const has = (...words) => words.every((w) => l.includes(w));
  const any = (...words) => words.some((w) => l.includes(w));

  if (any("sponsor", "visa sponsorship") || has("require", "visa")) return "requiresSponsorship";
  if (has("authorized", "work") || has("legally", "work") || has("work", "authorization")) return "workAuthorized";
  if (any("export control") || has("u.s. person") || has("us person")) return "usPersonExportControl";
  if (any("employment agreement", "non-compete", "noncompete", "post-employment", "restrictive covenant")) return "employmentAgreements";
  if (has("worked", "before") || has("previously", "worked") || has("consult", "before")) return "workedHereBefore";
  if (any("country of residence") || has("current", "country")) return "country";
  if (l.includes("linkedin")) return "linkedin";
  if (l.includes("github")) return "github";
  if (any("portfolio", "website", "personal site")) return "portfolio";
  if (has("preferred", "name") || has("name", "prefer")) return "preferredName";
  if (any("pronoun")) return "pronouns";
  if (has("gender") || l.includes("gender identity")) return "eeoGender";
  if (any("race", "ethnicity")) return "eeoEthnicity";
  if (l.includes("veteran")) return "eeoVeteran";
  if (l.includes("disability")) return "eeoDisability";
  if (any("salary", "compensation expectation", "expected pay", "desired salary")) return "salaryExpectation";
  if (any("notice period", "when can you start", "availability", "start date")) return "availability";
  if (has("willing", "relocate") || l.includes("relocation")) return "willingToRelocate";
  if (any("hybrid", "in-office", "onsite", "on-site")) return "willingToWorkHybrid";
  return null;
}

/** Build the answer for a single Greenhouse question.
 *  Returns { question, answers: [{name,value}], source, confidence, note }.
 *  confidence: 1 = certain (verbatim profile), 0.9 = deterministic rule,
 *  0.7 = AI free-text, 0 = unanswered (review). */
export function answerQuestion(q, profile, ai) {
  const fields = q.fields || [];
  const primary = fields[0] || {};
  const label = q.label || primary.name || "";
  const isSelect = fields.some((f) => (f.type || "").includes("select"));

  const out = (answers, source, confidence, note) => ({
    label, required: !!q.required, source, confidence, note: note || "", answers,
  });
  const unanswered = (note) => out([], SOURCE.NONE, 0, note);

  // ── Standard Greenhouse fields (stable `name`s) ────────────────────────────
  const name = primary.name || "";
  const std = {
    first_name: profile.firstName,
    last_name: profile.lastName,
    email: profile.email,
    phone: profile.phone,
  };
  if (name in std) {
    const v = std[name];
    return v ? out([{ name, value: v }], SOURCE.PROFILE, 1) : unanswered(`profile.${name} is empty`);
  }
  if (name === "resume" || fields.some((f) => f.name === "resume")) {
    return profile.resumePath
      ? out([{ name: "resume", value: profile.resumePath, isFile: true }], SOURCE.PROFILE, 1)
      : unanswered("no resume on file");
  }
  if (name === "cover_letter" || fields.some((f) => f.name === "cover_letter")) {
    // Filled later by the doc generator; optional so it never blocks.
    return out([], SOURCE.NONE, 0, "cover letter attached separately");
  }

  // ── Custom questions routed by label ───────────────────────────────────────
  const key = classify(label);

  // High-stakes compliance & identity → PROFILE ONLY, never AI.
  const profileMap = {
    requiresSponsorship: profile.requiresSponsorship,
    workAuthorized: profile.workAuthorized,
    usPersonExportControl: profile.usPersonExportControl,
    employmentAgreements: profile.employmentAgreements,
    country: profile.country,
    linkedin: profile.linkedin,
    github: profile.github,
    portfolio: profile.portfolio,
    preferredName: profile.firstName,
    pronouns: profile.pronouns,
    eeoGender: profile.eeoGender,
    eeoEthnicity: profile.eeoEthnicity,
    eeoVeteran: profile.eeoVeteran,
    eeoDisability: profile.eeoDisability,
    availability: profile.availability,
    willingToRelocate: profile.willingToRelocate,
    willingToWorkHybrid: profile.willingToWorkHybrid,
    salaryExpectation: profile.salaryExpectation,
  };

  if (key === "workedHereBefore") {
    // Almost always "No" for a new applicant; still a deterministic rule, not AI.
    if (isSelect) {
      const m = matchOption(primary, "No");
      return m ? out([{ name, value: m.value }], SOURCE.RULE, 0.9, "assumed not a prior employee")
        : unanswered('select has no "No" option');
    }
    return out([{ name, value: "No" }], SOURCE.RULE, 0.9);
  }

  if (key && key in profileMap) {
    const desired = profileMap[key];
    if (!desired) return unanswered(`profile has no value for ${key}`);
    if (isSelect) {
      const opts = key === "country" ? { synonyms: countryVariants(desired) } : {};
      const m = matchOption(primary, desired, opts);
      return m
        ? out([{ name, value: m.value }], SOURCE.PROFILE, 1)
        : unanswered(`"${desired}" is not an offered option for "${label}"`);
    }
    return out([{ name, value: desired }], SOURCE.PROFILE, 1);
  }

  // ── Free-text, non-compliance → AI (if available), else review ─────────────
  const isFreeText = fields.some((f) => (f.type || "").includes("text"));
  if (isFreeText && !isSelect) {
    if (ai && typeof ai.answerFreeText === "function") {
      // Caller supplies a sync-resolved cache; see apply-greenhouse.mjs.
      const cached = ai.get(label);
      if (cached) return out([{ name, value: cached }], SOURCE.AI, 0.7, "AI free-text");
    }
    // No AI answer available → park (never submit a blank required free-text).
    return q.required ? unanswered("free-text needs AI/manual answer") : out([], SOURCE.NONE, 0, "optional free-text skipped");
  }

  // Unknown select we can't safely map → review.
  return unanswered(`unrecognized ${isSelect ? "select" : "field"}: "${label}"`);
}

/** Map an entire form. Returns { answers: [...], review: [...] }. */
export function mapForm(questions, profile, ai) {
  const answers = [];
  const review = [];
  for (const q of questions) {
    const a = answerQuestion(q, profile, ai);
    answers.push(a);
    if (a.required && a.answers.length === 0) review.push(a);
  }
  return { answers, review };
}
