// answer-engine.mjs
//
// Maps a Greenhouse application form (the JSON returned by
// boards-api.greenhouse.io/.../jobs/{id}?questions=true) to concrete answers,
// using ONLY the applicant's saved profile for high-stakes fields and (later)
// AI for free-text. Every answer carries a source + confidence so the verifier
// can refuse to submit anything uncertain.
//
// Design rule for "no mistakes": when in doubt, DO NOT ANSWER. An unanswered
// required field parks the whole job for manual review instead of guessing.

import { fieldKind } from "./fieldkind.mjs";

/** Answer sources, most→least trustworthy. */
export const SOURCE = {
  PROFILE: "profile", // copied verbatim from saved settings — highest trust
  RESUME: "resume", // pulled from parsed resume
  RULE: "rule", // deterministic mapping (e.g. "worked here before" → No)
  AI: "ai", // generated by the model (free-text only)
  NONE: "none", // could not answer → forces review
};

const norm = (s) => (s || "").toString().trim().toLowerCase();

// Factually-equivalent country label variants. Safe to treat as identical —
// a form calling it "United States of America" and a profile saying "United
// States" are the same country, not a guess.
const COUNTRY_SYNONYMS = [
  ["united states", "united states of america", "usa", "u.s.a.", "u.s.", "us"],
  ["united kingdom", "uk", "u.k.", "great britain"],
];
function countryVariants(value) {
  const v = norm(value);
  const group = COUNTRY_SYNONYMS.find((g) => g.includes(v));
  return group ? group : [v];
}

// US state full name <-> two-letter abbreviation. Lets "California" match a
// dropdown that only offers "CA" (and vice versa). Factual equivalence, not a guess.
const US_STATES = {
  alabama: "al", alaska: "ak", arizona: "az", arkansas: "ar", california: "ca",
  colorado: "co", connecticut: "ct", delaware: "de", florida: "fl", georgia: "ga",
  hawaii: "hi", idaho: "id", illinois: "il", indiana: "in", iowa: "ia", kansas: "ks",
  kentucky: "ky", louisiana: "la", maine: "me", maryland: "md", massachusetts: "ma",
  michigan: "mi", minnesota: "mn", mississippi: "ms", missouri: "mo", montana: "mt",
  nebraska: "ne", nevada: "nv", "new hampshire": "nh", "new jersey": "nj",
  "new mexico": "nm", "new york": "ny", "north carolina": "nc", "north dakota": "nd",
  ohio: "oh", oklahoma: "ok", oregon: "or", pennsylvania: "pa", "rhode island": "ri",
  "south carolina": "sc", "south dakota": "sd", tennessee: "tn", texas: "tx",
  utah: "ut", vermont: "vt", virginia: "va", washington: "wa", "west virginia": "wv",
  wisconsin: "wi", wyoming: "wy", "district of columbia": "dc",
};
function regionVariants(value) {
  const v = norm(value);
  if (US_STATES[v]) return [v, US_STATES[v]];
  const full = Object.keys(US_STATES).find((k) => US_STATES[k] === v);
  return full ? [v, full] : [v];
}

/** Find the select option whose label matches `desired` (case-insensitive).
 *  Returns the option's stored value, or null if there is no exact match.
 *  We never fuzzy-pick a "close" option — a wrong compliance pick is the exact
 *  mistake we must avoid. */
function matchOption(field, desired, { synonyms = null } = {}) {
  const values = field.values || field.options || [];
  const wants = synonyms || [norm(desired)];
  const hit = values.find((v) => wants.includes(norm(v.label)));
  if (hit) return { value: hit.value, label: hit.label };
  return null;
}

/** Classify a custom question by its label so we can route it to the right
 *  profile field. Returns a key or null. Order matters (first match wins). */
function classify(label) {
  const l = norm(label);
  const has = (...words) => words.every((w) => l.includes(w));
  const any = (...words) => words.some((w) => l.includes(w));

  // "Authorized to work WITHOUT sponsorship" combines work auth AND sponsorship
  // need. Must be resolved from both fields, never from workAuthorized alone.
  if (has("authorized", "work") && l.includes("without") && (l.includes("sponsor") || l.includes("visa"))) return "authorizedWithoutSponsorship";
  // "Will you require/need sponsorship" -> requiresSponsorship. Deliberately does
  // NOT match "currently in a sponsored status" (a different, status question).
  if (/(require|need).{0,20}sponsor/.test(l) || /sponsorship.{0,20}(visa|now|future|employment)/.test(l) || has("will you", "sponsorship")) return "requiresSponsorship";
  // Specific current-visa-status questions cannot be answered from the generic
  // profile. Route to a status key that parks unless profile.visaStatus is set.
  if (/currently.{0,20}(status|visa)/.test(l) || l.includes("o-1") || l.includes("h1b") || l.includes("h-1b") || l.includes("f-1") || l.includes("opt") || l.includes("cpt") || (l.includes("student") && l.includes("status"))) return "currentVisaStatus";
  if (has("authorized", "work") || has("legally", "work") || has("work", "authorization")) return "workAuthorized";
  if (any("export control") || has("u.s. person") || has("us person")) return "usPersonExportControl";
  if (any("employment agreement", "non-compete", "noncompete", "post-employment", "restrictive covenant")) return "employmentAgreements";
  if (has("worked", "before") || has("previously", "worked") || has("consult", "before") || /have you (ever )?worked (at|for)/.test(l) || /worked (here|at this company)/.test(l)) return "workedHereBefore";
  if (/related to (a |an )?.*(employee|staff)/.test(l) || has("relative", "work here")) return "relatedToEmployee";
  if (any("sms", "whatsapp", "text message") && any("contact", "consent", "opt")) return "smsConsent";
  if (has("worked", "before") || has("previously", "worked") || has("consult", "before")) return "workedHereBefore";
  if (any("country of residence") || has("current", "country") || l === "country" || l === "country:") return "country";
  // Address / location (guard against look-alikes: citizenship, employment status).
  if (/\bcity\b/.test(l) && !l.includes("citizen")) return "city";
  if ((/\bstate\b|\bprovince\b/.test(l)) && !l.includes("united states") && !l.includes("status")) return "region";
  if (any("postal", "zip", "pincode", "pin code")) return "postalCode";
  if (has("address", "line 2") || any("apartment", "apt", "unit", "suite")) return "addressLine2";
  if (any("address line 1", "street address") || (l.includes("address") && !l.includes("email") && !l.includes("ip"))) return "addressLine1";
  if (any("how did you hear", "how you hear", "hear about", "referral source")) return "heardAboutUs";
  if (l.includes("linkedin")) return "linkedin";
  if (l.includes("github")) return "github";
  if (any("portfolio", "website", "personal site")) return "portfolio";
  if (has("legal", "first name") || has("legal", "given name")) return "legalFirstName";
  if (has("legal", "last name") || has("legal", "family name") || has("legal", "surname")) return "legalLastName";
  if (has("preferred", "name") || has("name", "prefer")) return "preferredName";
  if (any("pronoun")) return "pronouns";
  if (has("gender") || l.includes("gender identity")) return "eeoGender";
  if (any("race", "ethnicity")) return "eeoEthnicity";
  if (l.includes("veteran")) return "eeoVeteran";
  if (l.includes("disability")) return "eeoDisability";
  if (any("salary", "compensation expectation", "expected pay", "desired salary")) return "salaryExpectation";
  if (any("notice period", "when can you start", "availability", "start date")) return "availability";
  if (has("willing", "relocate") || l.includes("relocation")) return "willingToRelocate";
  if (any("hybrid", "in-office", "onsite", "on-site")) return "willingToWorkHybrid";
  return null;
}

/** Build the answer for a single Greenhouse question.
 *  Returns { question, answers: [{name,value}], source, confidence, note }.
 *  confidence: 1 = certain (verbatim profile), 0.9 = deterministic rule,
 *  0.7 = AI free-text, 0 = unanswered (review). */
export function answerQuestion(q, profile, ai) {
  const fields = q.fields || [];
  const primary = fields[0] || {};
  const label = q.label || primary.name || "";
  // Centralized field-kind detection (see fieldkind.mjs). A question is a
  // "select" if ANY of its fields offers fixed choices.
  const kinds = fields.map(fieldKind);
  const isSelect = kinds.some((k) => ["select", "multiselect", "boolean"].includes(k));

  const out = (answers, source, confidence, note) => ({
    label, required: !!q.required, source, confidence, note: note || "", answers,
  });
  const unanswered = (note) => out([], SOURCE.NONE, 0, note);

  // ── Standard Greenhouse fields (stable `name`s) ────────────────────────────
  const name = primary.name || "";
  const std = {
    first_name: profile.firstName,
    last_name: profile.lastName,
    email: profile.email,
    phone: profile.phone,
  };
  if (name in std) {
    const v = std[name];
    return v ? out([{ name, value: v }], SOURCE.PROFILE, 1) : unanswered(`profile.${name} is empty`);
  }
  if (name === "resume" || fields.some((f) => f.name === "resume")) {
    return profile.resumePath
      ? out([{ name: "resume", value: profile.resumePath, isFile: true }], SOURCE.PROFILE, 1)
      : unanswered("no resume on file");
  }
  if (name === "cover_letter" || fields.some((f) => f.name === "cover_letter")) {
    // Filled later by the doc generator; optional so it never blocks.
    return out([], SOURCE.NONE, 0, "cover letter attached separately");
  }

  // ── Custom questions routed by label ───────────────────────────────────────
  let key = classify(label);
  // A textarea/paragraph field must never get a yes/no or single-value profile
  // answer, even if its label contains a matching keyword (e.g. "office
  // preferences or geographic flexibility"). Route it to free text instead.
  if (kinds[0] === "longtext") key = null;

  // High-stakes compliance & identity → PROFILE ONLY, never AI.
  const profileMap = {
    requiresSponsorship: profile.requiresSponsorship,
    workAuthorized: profile.workAuthorized,
    usPersonExportControl: profile.usPersonExportControl,
    employmentAgreements: profile.employmentAgreements,
    country: profile.country,
    city: profile.city,
    region: profile.region || profile.state,
    postalCode: profile.postalCode || profile.zip,
    addressLine1: profile.addressLine1,
    addressLine2: profile.addressLine2,
    heardAboutUs: profile.heardAboutUs,
    smsConsent: profile.smsConsent,
    linkedin: profile.linkedin,
    github: profile.github,
    portfolio: profile.portfolio,
    preferredName: profile.preferredName || profile.firstName,
    legalFirstName: profile.firstName,
    legalLastName: profile.lastName,
    pronouns: profile.pronouns,
    eeoGender: profile.eeoGender,
    eeoEthnicity: profile.eeoEthnicity,
    eeoVeteran: profile.eeoVeteran,
    eeoDisability: profile.eeoDisability,
    availability: profile.availability,
    willingToRelocate: profile.willingToRelocate,
    willingToWorkHybrid: profile.willingToWorkHybrid,
    salaryExpectation: profile.salaryExpectation,
  };

  if (key === "workedHereBefore" || key === "relatedToEmployee") {
    // "No" for a new applicant with no relative at the company; a deterministic
    // rule, not AI.
    const why = key === "relatedToEmployee" ? "assumed no relative at the company" : "assumed not a prior employee";
    if (isSelect) {
      const m = matchOption(primary, "No");
      return m ? out([{ name, value: m.value }], SOURCE.RULE, 0.9, why)
        : unanswered('select has no "No" option');
    }
    return out([{ name, value: "No" }], SOURCE.RULE, 0.9, why);
  }

  // Authorized to work without sponsorship: resolve from BOTH fields.
  if (key === "authorizedWithoutSponsorship") {
    const req = norm(profile.requiresSponsorship);
    const auth = norm(profile.workAuthorized);
    let ans = null;
    if (req === "yes") ans = "No"; // needs sponsorship -> not authorized without it
    else if (req === "no" && auth === "yes") ans = "Yes";
    if (!ans) return unanswered("cannot resolve authorized-without-sponsorship from profile");
    if (isSelect) { const m = matchOption(primary, ans); return m ? out([{ name, value: m.value }], SOURCE.PROFILE, 1) : unanswered(`no "${ans}" option`); }
    return out([{ name, value: ans }], SOURCE.PROFILE, 1);
  }

  // Specific current-visa-status questions (O-1/H1B/F-1/OPT ...). Only answerable
  // if profile.visaStatus explicitly encodes it; otherwise PARK, never guess.
  if (key === "currentVisaStatus") {
    const vs = profile.visaStatus || {};
    const ll = norm(label);
    const isStudent = /f-1|opt|cpt|student|trainee|j1|j-1/.test(ll);
    const isSponsored = /o-1|h1b|h-1b|tn|e3|e-3|sponsored status/.test(ll);
    let ans = null;
    if (isStudent && vs.student != null) ans = vs.student ? "Yes" : "No";
    else if (isSponsored && vs.sponsored != null) ans = vs.sponsored ? "Yes" : "No";
    if (!ans) return unanswered("current visa status question needs your input");
    if (isSelect) { const m = matchOption(primary, ans); return m ? out([{ name, value: m.value }], SOURCE.PROFILE, 1) : unanswered(`no "${ans}" option`); }
    return out([{ name, value: ans }], SOURCE.PROFILE, 1);
  }

  // How did you hear: try the profile value, else the honest "Other" option.
  if (key === "heardAboutUs") {
    if (isSelect) {
      let m = profile.heardAboutUs ? matchOption(primary, profile.heardAboutUs) : null;
      if (!m) m = matchOption(primary, "Other");
      return m ? out([{ name, value: m.value }], SOURCE.RULE, 0.85, "how-you-heard best match") : unanswered("no matching option");
    }
    return out([{ name, value: profile.heardAboutUs || "Other" }], SOURCE.RULE, 0.85);
  }

  if (key && key in profileMap) {
    const desired = profileMap[key];
    if (!desired) return unanswered(`profile has no value for ${key}`);
    if (isSelect) {
      const opts = key === "country" ? { synonyms: countryVariants(desired) }
        : key === "region" ? { synonyms: regionVariants(desired) } : {};
      const m = matchOption(primary, desired, opts);
      return m
        ? out([{ name, value: m.value }], SOURCE.PROFILE, 1)
        : unanswered(`"${desired}" is not an offered option for "${label}"`);
    }
    return out([{ name, value: desired }], SOURCE.PROFILE, 1);
  }

  // ── Free-text, non-compliance → AI (if available), else review ─────────────
  const isFreeText = kinds.some((k) => ["text", "longtext"].includes(k));
  if (isFreeText && !isSelect) {
    if (ai && typeof ai.get === "function") {
      // Caller pre-computes AI answers and passes a { get(label) } cache so this
      // stays synchronous. See apply-flow.mjs (two-pass).
      const cached = ai.get(label);
      if (cached) return out([{ name, value: cached }], SOURCE.AI, 0.7, "AI free-text");
    }
    // No AI answer available → park (never submit a blank required free-text).
    return q.required ? unanswered("free-text needs AI/manual answer") : out([], SOURCE.NONE, 0, "optional free-text skipped");
  }

  // A required select with exactly one option (a mandatory acknowledgement)
  // has only one valid answer, so selecting it is not a guess.
  if (isSelect) {
    const opts = primary.values || primary.options || [];
    if (opts.length === 1) {
      return out([{ name, value: opts[0].value }], SOURCE.RULE, 0.9, "single-option acknowledgement");
    }
  }

  // Unknown select we can't safely map → review.
  return unanswered(`unrecognized ${isSelect ? "select" : "field"}: "${label}"`);
}

/** Map an entire form. Returns { answers: [...], review: [...] }. */
export function mapForm(questions, profile, ai) {
  const answers = [];
  const review = [];
  for (const q of questions) {
    const a = answerQuestion(q, profile, ai);
    answers.push(a);
    if (a.required && a.answers.length === 0) review.push(a);
  }
  return { answers, review };
}
